### ISSUE TITLE
Migrate to GitHub Actions

### ISSUE THREAD

**Issue by range-of-motion** [range-of-motion/budget#61]
I got in on the beta of GitHub Actions, should prolly migrate to that. I'll do that myself tho <3

**Comment by range-of-motion** [comment]
I think I'm doing a decent job, but I can't figure out how to set up a MySQL database to run the tests against?

```yml
name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Install Composer dependencies
        run: composer install --no-interaction

      - name: Set up .env file
        run: |
              cp .env.example .env
              php artisan key:generate
```
